version: 2
updates:
- package-ecosystem: npm
  directory: /
  open-pull-requests-limit: 10
  # Group packages into shared PR
  groups:
    aws-sdk:
      patterns:
        - '@aws-sdk/*'

    test:
      patterns:
        - '@testing-library/*'
        - 'cheerio'
        - 'supertest'
        - 'vitest'
        - 'puppeteer'
        - 'msw'
        - 'jsdom'

    lint:
      patterns:
        - '@types/eslint'
        - '@typescript-eslint/*'
        - 'eslint'
        - 'eslint-*'
        - 'stylelint'
        - 'stylelint-*'

    types:
      patterns:
        - '@types/*'

      # Exclude packages in other groups
      exclude-patterns:
        - '@types/aws-sdk'
        - '@types/eslint'
        - '@types/d3-*'

    webpack-plus-plugins-and-loaders:
      patterns:
        - 'webpack'
        - 'mini-css-extract-plugin'
        - 'css-minimizer-webpack-plugin'
        - 'compression-webpack-plugin'
        - 'webpack-node-externals'
        - 'webpack-cli'
        - 'nodemon-webpack-plugin'
        - 'sass-loader'
        - 'css-loader'
        - 'ts-loader'
    
    react:
      patterns:
        - 'react'
        - 'react-*'

    d3:
      patterns:
        - 'd3'
        - 'd3-*'
        - '@types/d3-*'
      
      # this is ESM only from v6. 
      exclude-patterns:
         - 'react-markdown'

  # Schedule run every Monday, local time
  schedule:
    interval: weekly
    time: '03:00'
    timezone: 'Europe/London'

  versioning-strategy: increase
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: github-action
