require: rubocop-rspec
inherit_gem:
  govuk-lint:
    - configs/rubocop/all.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4.2
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "test/**/*"
    - "**/spec/**/*"
    - "config/**/*"
Rails:
  Enabled: true
RSpec/MultipleExpectations:
  Description: Checks if examples contain far too many `expect` calls.
  Enabled: true
  Max: 20
  StyleGuide: http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/MultipleExpectations
RSpec/ExampleLength:
  Description: Checks for excessively long examples.
  Enabled: true
  Max: 30
  StyleGuide: http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ExampleLength
RSpec/VerifiedDoubles:
  Description: Prefer using verifying doubles over normal doubles.
  Enabled: false
  IgnoreSymbolicNames: false
  StyleGuide: http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/VerifiedDoubles
