export const owners = [
  '10 Downing Street',
  'British Council',
  'Cabinet Office',
  'Civil Aviation Authority',
  'College of Policing',
  'Crown Commercial Service',
  'Darlington Borough Council',
  'Defence Science and Technology Laboratory',
  'Department for Business, Energy & Industrial Strategy',
  'Department for Education',
  'Department for Environment, Food & Rural Affairs',
  'Department for International Trade',
  'Department for Transport',
  'Department for Work & Pensions',
  'Department of Finance Northern Ireland',
  'Department of Health & Social Care',
  'Derry Strabane District Council',
  'Disclosure Scotland',
  'Environment Agency',
  'Government Digital Service',
  'Government Equalities Office',
  'Government Office for Science',
  'Government Property Agency',
  'Hackney London Borough Council',
  'HM Revenue & Customs',
  'Home Office',
  'Homes England',
  'Kingston upon Thames London Borough Council',
  'London Borough of Camden',
  'Marine Management Organisation',
  'Methods',
  'Ministry of Defence',
  'Ministry of Housing, Communities and Local Government',
  'National Cyber Security Centre',
  'National Lottery Heritage Fund',
  'Natural England',
  'NHS Digital',
  'NHS England',
  'Northern Ireland Department for Communities',
  'Northern Ireland Department for the Economy',
  'Ofgem',
  'Ofsted',
  'Royal Air Force',
  'Student Awards Agency Scotland',
  'UK Export Finance',
  'UK Space Agency',
];
