export const owners = [
  '10 Downing Street',
  'Bristol City Council',
  'British Council',
  'Cabinet Office',
  'Chief Digital Information Office',
  'Civil Aviation Authority',
  'College of Policing',
  'Crown Commercial Service',
  'Darlington Borough Council',
  'Department for Business, Energy & Industrial Strategy',
  'Department for Education',
  'Department for Environment, Food & Rural Affairs',
  'Department for International Trade',
  'Department for Levelling Up, Housing & Communities',
  'Department for Transport',
  'Department for Work & Pensions',
  'Department of Finance Northern Ireland',
  'Department of Health & Social Care',
  'Derry Strabane District Council',
  'Disclosure Scotland',
  'Environment Agency',
  'Foreign, Commonwealth & Development Office',
  'Government Digital Service',
  'Government Equalities Office',
  'Government Office for Science',
  'Government Property Agency',
  'Greater London Authority',
  'Hackney London Borough Council',
  'HM Passport Office',
  'HM Revenue & Customs',
  'Home Office',
  'Homes England',
  'Kingston upon Thames London Borough Council',
  'London Borough of Camden',
  'Marine Management Organisation',
  'Ministry of Defence',
  'Ministry of Housing, Communities and Local Government',
  'Ministry of Justice',
  'National Cyber Security Centre',
  'National Lottery Heritage Fund',
  'Natural England',
  'NHS Digital',
  'NHS England',
  'Northern Ireland Department for Communities',
  'Northern Ireland Department for the Economy',
  'Ofgem',
  'Ofsted',
  'PaaS engagement',
  'Platform',
  'Public Health England',
  'Student Awards Agency Scotland',
  'UK Export Finance',
  'UK Research and Innovation',
  'UK Space Agency',
]
