---
name: pr-tests
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    env:
      NODE_ENV: development
      TEST_TIMEOUT: 60000

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version-file: "package.json"
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Test - Unit
        run: npm run test:unit

      - name: Lint
        run: npm run lint
